---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rook-application
  labels:
    app: rook-application
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      usage: development
  #clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
